### ISSUE TITLE
Still active

### ISSUE THREAD

**Issue by vkuehn** [varjolintu/mdBook-bujinkan-template#1]
Hi, do you still want to maintain that side/code ?

**Comment by varjolintu** [comment]
Sure. Is there anything to fix or add?

**Comment by vkuehn** [comment]
thiught there is not much content, just the names, is that the plan ?

**Comment by varjolintu** [comment]
That's the plan. This is just a template, and practitioners gotta fill the blanks by themselves :) My filled version is 137 pages right now. Of course that is not something you share. It's like your personal denshō.

**Comment by vkuehn** [comment]
ok thanks for the repo anyways, thought it's a great help !
However documenting the technics still does not provide the teaching you need.
I'll have a closer look

**Comment by varjolintu** [comment]
Yes, you still need the teaching. The point of the whole template was that when you write notes in seminars, those usually are not in "order" if you look at the school or its level. This template should help organizing your notes so they are in "order" and easier to find.

For example, I'm using this in a following way, separating possible different teachers or different versions with Henka heading:
<img width="1703" alt="Screenshot 2021-07-18 at 15 31 07" src="https://user-images.githubusercontent.com/24570482/126067305-0848ccdf-d4ec-4920-a741-ecf9492a9058.png">

**Comment by vkuehn** [comment]
will be a big book and than...once notes are done it will look ugly after changing some of them after years. Thought  one would have to fork yours and than update it in some digital format anyways
